### ISSUE TITLE
Add models: File and Commit

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-models#13]
A File shall have
- a path
- a Commit

A Commit shall have 
- shasum
- a Repository
- an author (User - optional)
- an editor (User - optional)
- an author-name
- an author-time
- an editor-name
- an editor-time

**Comment by ebolloff** [comment]
If we name the model `file` we have a conflict with Ruby's `File`. I named it `FileVersion` for now. Any suggetions @phyrog @eugenk?

**Comment by ebolloff** [comment]
Should the file have the `url_path` or just the `path`?

**Comment by eugenk** [comment]
How about RepositoryFile?

**Comment by eugenk** [comment]
Every model should have a `url_path` which points to the resource on the web. A `File` should have a `path` as well, which is the path of the file inside the repository. Maybe we should call it `filepath`, but it seems a little redundant to me.

**Comment by ebolloff** [comment]
We'll stay with `FileVersion`.
