### ISSUE TITLE
Add model: Team

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-models#39]
For now, a Team has many users and a User has many Teams.

**Comment by tillmo** [comment]
Team is the same as Organisation on github? I.e. Team and User names are the ones appearing in LocIds before the repo name?

**Comment by eugenk** [comment]
Yes.

**Comment by eugenk** [comment]
We can call it Organization, too.

**Comment by tillmo** [comment]
yes, let us do this. Many people will know this from github.
