### ISSUE TITLE
Change data model

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-models#58]
We want to:

- remove the `Commit` model
- make `FileVersion` a stand-alone object that has the fields `commit_sha` and `path` (both String)

The reasoning for this is, that the `Commit` model is just a sort of cache to retrieve the users associated with a commit easier. This however can lead to problems when users change their email addresses, since we would have to walk through all commits and associate it to the user and remove the old associations. It is also premature optimization, as we currently don't know if querying users by email address on every commit access is actually as bad as we imagined.

@eugenk will upload a photo of this in the comments.

**Comment by tillmo** [comment]
I do not understand the reasoning here. 1) why is the `Commit` model just a cache for retrieving users of commits? Couldn't it also be used for representing information about commits (e.g. parent commits, list of files changed by a commit etc.) in a beneficial way (i.e. speedup w.r.t. calling rugged, better searchability, ...)? 2) Why is the proposed alternative using `FileVersion` better? How can it solve the problem that users may change email addresses?

**Comment by phyrog** [comment]
Sure we could save more information about the commit in the model, but we still need to query the git repo for the content of the commit anyway. We can then also access all the commit metadata (committer, pusher, author, parent commits, ...) and don't need to query them from the database. It's possible that there are situations that are faster in the database, but for now this would just be premature optimization, as we don't know yet how fast the `gitlab_git` code would be in these situations.

If we later decide that we indeed need a commit model to be fast enough, we can still write a migration that creates database entries for each commit in each repository. Or we could use a different, more general caching solution that can be used elsewhere in the code as well (e.g. with redis).

FileVersion would not get the metadata from the commit, but only the sha-hash of the commit and the path of the file in the repository. That's enough to get the file version when we `GET /ada/repo/ref/<some sha hash>/tree/path/to/the/file`. No need for a separate commit model here.

The only other case I can think of now would be getting the history of a branch, where we would not need to send the file contents, but we would still need the git repo to traverse the branch upwards to gather all commit ids, as branches are not saved in the database. Again, another kind of caching of this data might be better here.

The problem with the email addresses is solved by just matching the email address from the git repository to the email addresses of the users. When a user changes his email address, the email address no longer matches the one in the repository and we don't return the user for this commit. On the other side, all commits that already include the new email address automatically connect to the user (instead of using the primary key of the user for the association between the data, the email address itself is the foreign key in the commit, so to say).

**Comment by eugenk** [comment]
Here is the announced picture:
![data model - document - cropped](https://cloud.githubusercontent.com/assets/339751/23644135/ef2436c4-0305-11e7-80e2-430f1136cfa3.jpg)
The attributes `commit_sha` and `path` should be part of `FileVersion`, though.
